# Generated by Django 5.2.17 on 2026-09-26 15:37

import django.db.models.deletion
import shop.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        default=shop.models.generate_order_number,
                        editable=False,
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("client_id", models.CharField(db_index=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Pending payment"),
                            ("paid", "Paid"),
                            ("payment_failed", "Payment failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending_payment",
                        max_length=20,
                    ),
                ),
                ("customer_name", models.CharField(max_length=120)),
                ("phone", models.CharField(max_length=12)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=80)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[("standard", "Standard"), ("express", "Express")],
                        default="standard",
                        max_length=10,
                    ),
                ),
                ("subtotal", models.PositiveIntegerField()),
                ("delivery_fee", models.PositiveIntegerField()),
                ("discount", models.PositiveIntegerField(default=0)),
                ("total", models.PositiveIntegerField()),
                ("promo_code", models.CharField(blank=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("percent", "Percent off"),
                            ("flat", "Flat amount off"),
                        ],
                        default="percent",
                        max_length=10,
                    ),
                ),
                (
                    "value",
                    models.PositiveIntegerField(
                        help_text="Percent (1-100) or KES amount"
                    ),
                ),
                (
                    "max_discount",
                    models.PositiveIntegerField(
                        blank=True, help_text="Cap in KES (percent codes)", null=True
                    ),
                ),
                ("min_subtotal", models.PositiveIntegerField(default=0)),
                ("description", models.CharField(blank=True, max_length=120)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=200)),
                ("thumbnail", models.URLField(blank=True, max_length=500)),
                ("unit_price", models.PositiveIntegerField()),
                ("quantity", models.PositiveIntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shop.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=12)),
                (
                    "amount",
                    models.PositiveIntegerField(
                        help_text="Amount actually requested from M-Pesa"
                    ),
                ),
                ("merchant_request_id", models.CharField(blank=True, max_length=64)),
                ("checkout_request_id", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled by user"),
                            ("timeout", "Timed out"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("result_code", models.CharField(blank=True, max_length=16)),
                ("result_desc", models.CharField(blank=True, max_length=255)),
                ("mpesa_receipt_number", models.CharField(blank=True, max_length=32)),
                ("transaction_date", models.CharField(blank=True, max_length=20)),
                ("raw_callback", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_queried_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="shop.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
