# Generated by Django 5.2.17 on 2026-09-26 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_seed_promo_codes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.PositiveIntegerField(db_index=True)),
                ("client_id", models.CharField(db_index=True, max_length=64)),
                ("product_title", models.CharField(blank=True, max_length=200)),
                ("product_thumbnail", models.URLField(blank=True, max_length=500)),
                ("reviewer_name", models.CharField(max_length=80)),
                ("rating", models.PositiveSmallIntegerField()),
                ("comment", models.TextField(max_length=1000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "moderation_note",
                    models.CharField(
                        blank=True,
                        help_text="Shown to the customer if rejected",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("moderated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to="shop.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("client_id", "product_id"),
                        name="one_review_per_customer_product",
                    )
                ],
            },
        ),
    ]
